"""empty message

Revision ID: fa6df1f5dc1a
Revises: 9c4c207bbcdf
Create Date: 2019-03-10 17:21:33.919880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa6df1f5dc1a'
down_revision = '9c4c207bbcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_test', table_name='users')
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.create_index('ix_users_test', 'users', ['test'], unique=True)
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
